### ISSUE TITLE
bug in Filterbank.py

### ISSUE THREAD

**Issue by jhorrell** [ewanbarr/sigpyproc#1]
Hi Ewan,

The toFile() method is failing for a FilterbankBlock. Problem is a missing "header" in line 558 of Filterbank.py:

Currently reads: out_file = self.prepOutfile(filename,back_compatible=back_compatible)

Should be (I think): out_file = self.header.prepOutfile(filename,back_compatible=back_compatible)

Regards,
Jasper (jasper at ska dot ac dot za)

PS. Am trying to find a neat way to chop off the edges of my band and then write out to file again to work with that file in future. Did not seem to be a neat way to do this. Best seemed to be something like the below, but crashes due to above bug and also does not seem to read back in properly as a filterbank file (tested by fil.bandpass()) even after "fixing" the bug:

ln [1]: from sigpyproc.Readers import FilReader

In [2]: fil  = FilReader("vela_test.fil")

In [3]: bl = fil.readBlock(0,fil.header.nsamples)

In [4]: shape(bl)
Out[4]: (1024, 112640)

In [5]: bl_trimmed = bl[200:800].toFile()

ln [6]: bl_trimmed.toFile()

---

AttributeError                            Traceback (most recent call last)
<ipython-input-4-21d9979e097b> in <module>()
----> 1 bl_trimmed.toFile()

/Users/jasper/pulsar_software/sigpyproc/lib/python/sigpyproc/Filterbank.pyc in toFile(self, filename, back_compatible)
    556         if filename is None:
    557             filename = "%s_%d_to_%d.fil"%(self.header.basename,self.header.tstart,self.header.mjdAfterNsamps(self.shape[1]))
--> 558         out_file = self.prepOutfile(filename,back_compatible=back_compatible)
    559         out_file.cwrite(self)
    560         return filename

AttributeError: 'FilterbankBlock' object has no attribute 'prepOutfile'

**Comment by ewanbarr** [comment]
Hey,

Thanks for the heads up, you are quite correct about the bug. I noticed
this a while ago, but I must have forgotten to update the repository. I
will do it asap.

I am not sure the method that you are using to strip the band edges is the
most appropriate. You may be better just setting those channels to all
zeros.

The reason you are getting a crash when you try to use the data written
after the fix is that you have not update the file header to reflect the
fact that A.) you now have a different number of channels and B.) The data
is now in 32-bits instead of whatever it was before. You can update the
header using a keyword for prepOutfile.

When I update the repository I'll look at adding a small function to
provide the ability to strip the band edges.

Cheers,
Ewan

**Comment by jhorrell** [comment]
Thanks. The ability to strip the band edges would be most handy if implemented on the FilReader. That way I would be able to do (in example above), fil.fold(), fil.collapse() etc. with the trimmed band. I guess some sort of header update would be needed to go with that.

If instead, I apply fil.readBlock() and then chop the output of that, then some of these other handy methods are no longer available and one has to track indices all through the code.

PS. Any plans to implement a reader to enable greater interoperability with the psrchive tools? Have been finding it painful to move between formats/packages.

PPS. Thanks for such a handy package. It has been really excellent in enabling me to play around with the signals, try out some search strategies, make pyplot plots etc.

**Comment by jhorrell** [comment]
PPPS. Sort of related to chopping bands, have been thinking about how best to implement some sort of RFI flagging  on top of sigpyproc/prior to sigpyproc. A bit like what PRESTO has with rfifind with its output rfifind.mask. All handy things when teasing signals out of noise. Setting things to zero sometimes messes up the stats so perhaps options to set to median values etc? Once again, it would be good to be able to implement something which largely leaves the rest of the sigpyproc functionality intact after applying the mask. One approach might be to implement something that works directly on the input filterbank file, modifies it somehow, saves and then carry on as per normal.

Any thoughts on that?

**Comment by ewanbarr** [comment]
The best way to do and RFI filter in a sigpyproc framework would be to
write out a cleaned filterbank prior to doing further data analysis. This
is probably slower than implementing an on the fly method, but it will be a
hell of a lot less work. The way to do this would be to read through the
file in blocks using:

for nsamps,ii,data in self.readPlan(blocksize):

sidenote: This is the standard sigpyproc way of reading through a
filterbank file. Here "data" is just a standard numpy array containing that
block of the file.

Then for each channel calculate the time domain statistics (there is
already a c function that does this called "getStats" which is called from
a Filterbank method called "getStats"). I would just flag data points that
are X sigma above the mean in the time domain. You can also look at the
block in the Fourier domain, but you would have to transpose the block
first to get the channels contiguous and you would need to write an FFTW
function to batch FFT the channels.

I would not recommend replacing your flagged data with the median. Most
people replace flagged data with Gaussian noise. To get that you will first
need the standard deviation and mean of each channel in the block (which
"getStats" will give you). Then you can use the Mersenne Twister algorithm
which is in the c_src directory. That will let you generate the replacement
data.

Another way to do this may be (depending on if you care how long it takes
to run) to split the data into channels ("splitToChans"). Then FFT the
channels and rip out any channel that has greater than X signals with
greater than X S/N. You can also do the time domain analysis at this stage
and write out a sample mask to be applied later. The benefit here is that
most of this can be done in python without having to write a C function.
You would still need to apply the filter though...

As to the other questions:

> > > Any plans to implement a reader to enable greater interoperability with
> > > the psrchive tools? Have been finding it painful to move between
> > > formats/packages.

Not really. There are already python bindings for psrchive, which read out
the archives as numpy arrays, so there is some interoperability already.
The truth is that sigpyproc has only been designed to handle common
searching formats so far. The cross over with timing data has never been an
issue.

> > > PPS. Thanks for such a handy package. It has been really excellent in
> > > enabling me to play around with the signals, try out some search
> > > strategies, make pyplot plots etc.

No worries, it was a learning experience for me, so forgive me any oddities
in the code.

I'll send you a mail when I have pushed the update.

Ewan

**Comment by ewanbarr** [comment]
So there is now a channel masking method of the Filterbank class (the repo
has been updated):

```
    #Slow python only version

    #a C function would do this much faster

    if outfilename is None:
        outfilename = "%s_masked.fil"%(self.header.basename)
    out_file =
```

self.header.prepOutfile(outfilename,back_compatible=back_compatible)
        for nsamps,ii,data in self.readPlan(gulp): #data here is time major
filterbank array
            for jj,chan in enumerate(chanmask):
                if chan==0:
                    data[jj::self.header.nchans] = 0
            out_file.cwrite(data)
        return out_file.name

by replacing the for jj,chan loop you with a C function call you could
probably speed this up by a factor of 2 or 3. The chanmask is just any
iterable of 1s and 0s which is nchans long. 1 denotes a channel to keep, 0
denotes a channel to zero.

I have implemented it this way because there is no difference between
ripping a channel out of a filterbank and zeroing that channel. Similarly
you can use this function to zero any bad channel, not just those at the
edge of the band. This preserves frequency continuity between filterbank
channels.

I gave it a quick test and it seemed to work as expected. Give me a shout
if you have any problems with it.

Also, if you are going to be developing parts of the code, I am happy to
add any contributions to the main repository. Similarly I am happy to
provide assistance if you can't find a way to do something within the
sigpyproc framework.

Cheers,
Ewan

**Comment by ewanbarr** [comment]
Hey,

Disregard the code in the previous email, I updated the function above to
make a C call:

if outfilename is None:
            outfilename = "%s_masked.fil"%(self.header.basename)
        mask = np.array(chanmask).astype("ubyte")
        out_file =
self.header.prepOutfile(outfilename,back_compatible=back_compatible)
        for nsamps,ii,data in self.readPlan(gulp):
            self.lib.maskChannels(as_c(data),
                                  as_c(mask),
                                  C.c_int(self.header.nchans),
                                  C.c_int(nsamps))
            out_file.cwrite(data)
        return out_file.name

Where the C function looks like:

void maskChannels(unsigned char\* inbuffer,
                  unsigned char\* mask,
                  int nchans,
                  int nsamps)
{
  int ii,jj;
  for (ii=0;ii<nchans;ii++){
    if (mask[ii] == 0){
      for (jj=0;jj<nsamps;jj++){
        inbuffer[jj*nchans+ii] = 0.0;
      }
    }
  }
}

Cheers,
Ewan

**Comment by jhorrell** [comment]
Hey,

I was just testing the previous version and about to report how well it was working for me :) Think the new mask will solve most of my RFI issues as well, but may give the stats on time series approach a go soon too.

Will update.

Thanks for all the prompt action. I can now see my pulsar with the mask applied!

PS. Until the new method to apply the mask, it was never too clear to me how to actually write a sigproc filterbank format file from within sigpyproc. I see that the code for the new method shows how to do this. Would be handy at times to be able to make a smaller time/channel selection and write out to same format too (to be able to play with the data file on smaller machine, etc).

**Comment by ewanbarr** [comment]
No worries.

On the PS., it is already possible to make a smaller time selection by
using the readBlock method followed by the toFile method. I cannot
immediately see any reason why you would need to remove channels from the
file instead of setting them to zero. These channels do not add any noise
or signal during dedispersion or collapsing of the file.

If you really needed this functionality, you could change the toFile method
of the FilterbankBlock class from:

out_file = self.header.prepOutfile(filename,back_compatible=back_compatible)
out_file.cwrite(self)
return filename

to something like:

header_update = {"fch1",<frequency of new top channel>,
                          "nchans",self.shape[0]}
out_file = self.header.prepOutfile(filename, header_update ,
back_compatible=back_compatible)
out_file.cwrite(self)
return filename

FilterbankBlock is just a subclass of numpy.ndarray, so slicing notation
works, there is just no automatic update to the header parameters when
slicing. If you manually update the parameters, or add a couple of lines in
**array_finalize** that do this automatically, then when you write the file
the header should correctly describe the data.

Ewan

**Comment by jhorrell** [comment]
Hi Ewan,

Zero'ing freq channels is fine for now. The main reason for chopping them out would be to save on computing / network resources in my case.

Re the smaller time selection (need this since one of my files is a bit broken towards the end), readBlock() followed by toFile() (which is VERY slow), followed by reading back in using FilReader does not seem to be working properly. For example:

In[119]: fil = FilReader("my_original_filterbank_file.fil")

In[120]: bl2 = fil.readBlock(0,500)

In [121]: shape(bl2)
Out[121]: (1024, 500)

In [122]: bl2.toFile("test.fil")
Out[122]: 'test.fil'

In [123]: fil2 = FilReader("test.fil")

In [124]: plot(fil2.bandpass())

![fil2_bandpass](https://f.cloud.github.com/assets/1232928/1368795/8b44deea-39c0-11e3-93b3-45a29af003d3.png)

Which does not look anything like the bandpass I would expect.

Here is fil2's header. The number of samples is wrong (2000 instead of 500) and nbits = 8, but 32 bit numbers seem to be written by toFile(). Resetting these to 500 and 32 in the header, however, still does not improve the bandpass output.

In [125]: fil2.header
Out[125]: 
{'az_start': 0.0,
 'bandwidth': 400.0,
 'basename': 'test',
 'data_type': 1,
 'dec': '00:00:00.0000',
 'dec_deg': 0.0,
 'dec_rad': 0.0,
 'dtype': '<u1',
 'extension': '.fil',
 'fbottom': 1622.1953125,
 'fcenter': 1822.1953125,
 'fch1': 2022.0,
 'filelen': 2048338,
 'filename': 'test.fil',
 'foff': -0.390625,
 'ftop': 2022.1953125,
 'hdrlen': 338,
 'ibeam': 0,
 'machine_id': 1,
 'nbeams': 0,
 'nbits': 8,
 'nbytes': 2048000,
 'nchans': 1024,
 'nifs': 1,
 'nsamples': 2000,
 'obs_date': '26/04/2011',
 'obs_time': '18:06:19.00000',
 'ra': '00:00:00.0000',
 'ra_deg': 0.0,
 'ra_rad': 0.0,
 'rawdatafile': '',
 'source_name': 'Fake',
 'src_dej': 0.0,
 'src_raj': 0.0,
 'telescope_id': 1,
 'tobs': 0.08192,
 'tsamp': 4.096e-05,
 'tstart': 55677.75438657407,
 'za_start': 0.0}

Cheers,
Jasper

**Comment by ewanbarr** [comment]
ahh, I see the problem, and luckily it is easy to fix. There was a missing
keyword argument from prepOutfile. Also the data needed to be transposed to
be written out in Filterbank format. I have updated and pushed to the
repository.

I am not totally surprised at how slow the FilReader.readBlock.toFile
combination is, as the data goes to 32-bits in python which is slow. When
you say slow, how slow do you mean. I have just done a quick benchmark here
and I get:

In [10]: %timeit
FilReader("2009-03-08-01:24:54.fil").readBlock(0,512).toFile("test.fil")
100 loops, best of 3: 16.2 ms per loop

which isn't too bad.

If you don't require any on the methods of FilterbankBlock, you could just
use the readPlan function (which returns a generator object that reads
through the file). You can set the first sample and the number of samples
read by readPlan and it will keep the data in 8-bit, time-major format,
meaning that all you are doing is reading and directly writing. This is
already implemented in the split method of the Filterbank class (I
apologise, as I had forgotten that I had written this method).

 def split(self,start,nsamps,filename=None,gulp=1024,back_compatible=True)

Example usage:

In [14]: x = FilReader("2009-03-08-01:24:54.fil")

In [15]: x.split(0,512,filename="test.fil")

## Filterbank reading plan:

Called on file:        2009-03-08-01:24:54.fil
Called by:             split
Number of samps:       512
Number of reads:       1
Nsamps per read:       512
Nsamps of final read:  0
Nsamps to skip back:   0

Execution time: 0.011077 seconds

Out[15]: 'test.fil'

Due to some overhead in creating the reading plan instance, this is ~1 ms
slower on my machine than the FilterbankBlock way above. However, if you
have an I/O bottleneck, then this will be a faster method.

Cheers,
Ewan

**Comment by jhorrell** [comment]
Thanks, Ewan. Seems to have fixed the problem.

toFile() timings below (using an SSD). Think I was playing with large num samples previously which is what is a lot slower. Very non-linear from 1,08 sec to 57.6 secs (might be some system issue?).

In [87]: %timeit FilReader("test.fil").readBlock(0,512).toFile("test_block.fil") 
100 loops, best of 3: 13.6 ms per loop

In [88]: %timeit FilReader("test.fil").readBlock(0,5120).toFile("test_block.fil")
10 loops, best of 3: 92.9 ms per loop

In [89]: %timeit FilReader("test.fil").readBlock(0,51200).toFile("test_block.fil")
1 loops, best of 3: 1.08 s per loop

In [90]: %timeit FilReader("test.fil").readBlock(0,512000).toFile("test_block.fil")
1 loops, best of 3: 57.6 s per loop

I had also forgotten about the split method, noticed earlier, and this is what is needed since keeps the files smaller (8-bit, in my case). Thanks for the reminder.

Many thanks once again for the prompt attention. Good to see this is all being dealt with under git sigpyproc issue 1 :)

Jasper

**Comment by ewanbarr** [comment]
Its good to get a proper bug report, rather than people just sticking their
heads around the office door. Its good for the records.

On timings:

In [3]: %timeit
FilReader("2009-03-08-01:24:54.fil").readBlock(0,512).toFile("test.fil")
10 loops, best of 3: 17.4 ms per loop

In [4]: %timeit
FilReader("2009-03-08-01:24:54.fil").readBlock(0,5120).toFile("test.fil")
10 loops, best of 3: 48.3 ms per loop

In [5]: %timeit
FilReader("2009-03-08-01:24:54.fil").readBlock(0,51200).toFile("test.fil")
1 loops, best of 3: 603 ms per loop

In [6]: %timeit
FilReader("2009-03-08-01:24:54.fil").readBlock(0,512000).toFile("test.fil")
1 loops, best of 3: 5.67 s per loop

So I don't get anywhere near the same nonlinearity as you. I suspect you
are right about it being a system thing (maybe data going out of cache).
Python can get really resource heavy times.
The readPlan function will give a big speedup (x5) if that is the case:

In [17]: out = x.header.prepOutfile("test.fil")

In [18]: %timeit
out.cwrite(FilReader("2009-03-08-01:24:54.fil").readPlan(512000).next()[2])

1 loops, best of 3: 1.07 s per loop

Anyway, good luck and happy coding,

Ewan

**Comment by rubbyaworka** [comment]
Hi Ewan,

I am new to the sigpyproc software.
I have already installed it in python 3
please how do I use it to analyse .fil data
Thank you.
